apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: testdb
spec:
  ports:
  - port: 27017
    protocol: TCP
  externalIPs: 
    - 192.168.6.153    
  selector:
    appdb: testdb
